SPARQL """
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?person WHERE { 
     ?person wdt:P31 wd:Q5; 
             wdt:P39 wd:Q10655178 
} limit 5
 """@:SwedishMP